
{{- if contains $.Values.buildScope "cloud" }}

apiVersion: v1
kind: Service
metadata:
  name: {{ include "smtc.db.name" . }}-service
  labels:
    app: {{ include "smtc.db.name" . }}
spec:
  ports:
  - port: 9200
    protocol: TCP
    name: dsl
  - port: 9300
    protocol: TCP
    name: transport
  selector:
    app: {{ include "smtc.db.name" . }}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smtc.db.name" . }}
  labels:
     app: {{ include "smtc.db.name" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "smtc.db.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "smtc.db.name" . }}
    spec:
      enableServiceLinks: false
      containers:
        - name: {{ include "smtc.db.name" . }}
          image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9200
            - containerPort: 9300
          env:
            {{- if gt (int .Values.noffices) 1 }}
            - name: "cluster.name"
              value: "db-cluster"
            - name: "node.name"
              value: "cloud-db"
            - name: "node.master"
              value: "true"
            - name: "node.data"
              value: "true"
            - name: "node.attr.zone"
              value: "cloud"
            - name: "ES_JAVA_OPTS"
              value: "-Xms2048m -Xmx2048m"
{{- if (ne .Values.connector.cloud "") }}
            - name: "transport.port"
              value: "9300"
            - name: "transport.publish_host"
              value: "{{ .Values.connector.cloud }}"
            - name: "transport.publish_port"
              value: "9300"
{{- end }}
            {{- else }}
            - name: "discovery.type"
              value: "single-node"
            {{- end }}
            - name: "action.auto_create_index"
              value: "0"
            - name: NO_PROXY
              value: "*"
            - name: no_proxy
              value: "*"
          volumeMounts:
            - mountPath: /etc/localtime
              name: timezone
              readOnly: true
      initContainers:
        - name: init-volume-sysctl
          image: busybox:latest
          command: ["sh","-c","sysctl -w vm.max_map_count=262144 && ulimit -n 65535 && ulimit -u 4096"]
          securityContext:
            privileged: true
      volumes:
          - name: timezone
            hostPath:
                path: /etc/localtime
                type: File
      {{ include "smtc.platform.node-selector" . }}

{{- end }}
