
{{ $ServiceIntervalSmartUpload := 120 }}

{{- range $scenarioIdx, $scenarioName := $.Values.scenario }}
{{- $args := dict "scenarioName" $scenarioName "Values" $.Values }}
{{- range $officeIdx := until ( int ( include "smtc.noffices" $args ) ) }}
{{- $officeName := printf "%s-office%d" $scenarioName $officeIdx }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $officeName }}-smart-upload
  labels:
     app: {{ $officeName }}-smart-upload
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ $officeName }}-smart-upload
  template:
    metadata:
      labels:
        app: {{ $officeName }}-smart-upload
    spec:
      enableServiceLinks: false
      containers:
        - name: {{ $officeName }}-smart-upload
          image: {{ $.Values.registryPrefix }}smtc_smart_upload:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
                cpu: "100m"
            limits:
                cpu: "200m"
          env:
            - name: QUERY
              value: "time>={{ mul $ServiceIntervalSmartUpload 1000 }} where objects.detection.bounding_box.x_max-objects.detection.bounding_box.x_min>0.01"
            - name: INDEXES
              value: "recordings,analytics"
            - name: OFFICE
              {{- $args := dict "scenarioName" $scenarioName "Values" $.Values "officeIdx" $officeIdx }}
              {{- include "smtc.env.office" $args }}
            - name: DBHOST
              {{- $args := dict "officeName" $officeName "Values" $.Values }}
              {{- include "smtc.env.dbhost" $args }}
            - name: SMHOST
              value: "http://{{ $officeName }}-storage-service:8080/recording"
            - name: CLOUDHOST
              value: "http://cloud-storage-service:8080/recording"
            - name: SERVICE_INTERVAL
              value: "{{ $ServiceIntervalSmartUpload }}"
            - name: UPDATE_INTERVAL
              value: "5"
            - name: SEARCH_BATCH
              value: "3000"
            - name: UPDATE_BATCH
              value: "500"
            - name: NO_PROXY
              value: "*"
            - name: no_proxy
              value: "*"
          volumeMounts:
            - mountPath: /etc/localtime
              name: timezone
              readOnly: true
      volumes:
          - name: timezone
            hostPath:
                path: /etc/localtime
                type: File
      {{ include "smtc.platform.node-selector" $ }}
---

{{- end }}
{{- end }}
